{% set version = "1.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spocc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spocc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spocc/spocc_{{ version }}.tar.gz
  sha256: af4b398dc02522629b9fee697ccf640b7654330419a8f94cb5d1c7d17c8784fc

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crul
    - r-data.table
    - r-jsonlite
    - r-lubridate
    - r-rebird
    - r-rgbif
    - r-ridigbio
    - r-rvertnet
    - r-s2
    - r-tibble
    - r-wk
    - r-whisker
  run:
    - r-base
    - r-crul
    - r-data.table
    - r-jsonlite
    - r-lubridate
    - r-rebird
    - r-rgbif
    - r-ridigbio
    - r-rvertnet
    - r-s2
    - r-tibble
    - r-wk
    - r-whisker

test:
  commands:
    - $R -e "library('spocc')"           # [not win]
    - "\"%R%\" -e \"library('spocc')\""  # [win]

about:
  home: https://github.com/ropensci/spocc (devel), https://ropensci.github.io/spocc/ (user manual)
  license: MIT
  summary: A programmatic interface to many species occurrence data sources, including Global Biodiversity Information Facility ('GBIF'), 'USGSs' Biodiversity Information Serving Our Nation ('BISON'), 'iNaturalist', Berkeley 'Ecoinformatics' Engine, 'eBird', Integrated Digitized 'Biocollections' ('iDigBio'), 'VertNet', Ocean
    'Biogeographic' Information System ('OBIS'), and Atlas of Living Australia ('ALA'). Includes functionality for retrieving species occurrence data, and combining those data.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
